name: Scrape Table Sums

on: [push, workflow_dispatch]

jobs:
  playwright-sum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Scrape table sums and print total (23f2002348@ds.study.iitm.ac.in)
        run: node scrp.js
